

<?php 

 $img = $this->getMediaUrl().'/product/large_T-shurt.jpg';
echo $block->showData();?>

<div class="products wrapper grid products-grid">
<ol class="products list items product-items">
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 	</li>
 	<li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 </li>
 <li class="item product product-item">
 	<div class="product-item-info">
 		<img src="<?= $img ?>" alt="T-shurt" >
 	</div>
 </li>
</ol>
</div>
  

  
  
